### PR TITLE
Improve 0.19.x

### PR DESCRIPTION
**Pull request by ethanfrey**
Add some docs and patch the issue with floats in strconv

### CODE REVIEW

**Comment by fdymylja** [comment]
I realised there's a problem (that I introduced) whilst trying this out, example: `hex` package uses ParseFloat from strconv which appears to be missing. I will fix it as soon as I can.

We can merge as is if you want an open an issue for the fix.

**Comment by ethanfrey** [comment]
Just push your changes to this branch.
No rush to merge. I just didn't want them to get lost

**Comment by ethanfrey** [comment]
No rush, just replacing #1 with something we can merge.

**Comment by fdymylja** [comment]
Reporting here my findings.

I realised the reason for which there are floats leaking from reflection is because of the tinygo runtime package, ref: https://github.com/confio/tinygo/blob/improve-0.19/src/runtime/interface.go#L57. This switch for the cases of float and complex leaks float ops.

So, I would propose to: rollback changes in strconv (which means deleting the package and the code which does package merging specifically for cosmwasm).

Then we have 2 possible solutions:

1. Ignore what is happening here by simply stripping the floats, those lines are never going to get hit, because a valid cosmwasm contract does not have floats.
     - pros: less maintenance burden for us.
     - cons: we introduce an idea that, if you see floats just ignore those they're going to get stripped away. Which IMVHO is          not always the correct behaviour, as you might have code that might behave unexpectedly, and I think we want devs to investigate floats in their own code, and so we should make an effort to avoid the most common float leakage cases (interface comparison in this case).
     
2. Address the problem and remove the float leaking part from interface comparison code.
    - pros: if floats leak devs are more incentivised to investigate the code. Cosmwasm is not leaking floats, your code or some external lib you are importing is doing it.
    - cons: extra maintenance burden for us. ( I mean for this specific case the maintenance burden is not meaningful, yet )

**Comment by ethanfrey** [comment]
Great work @fdymylja 

I made a new build and tested the whole pipeline in cosmwasm-go and the integration tests.

Works perfect!

**Pull request merged**
